ProjetDotnet/Controllers/CongeController.cs
using ProjetDotnet.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetDotnet.Data;
using Microsoft.AspNetCore.Authorization;

namespace ProjetDotnet.Controllers
{
    [Authorize]
    public class CongeController : Controller
    {
        private readonly GestionRHContext context;

        public CongeController(GestionRHContext context)
        {
            this.context = context;
            
        }

        
        // GET: CongeController
        public ActionResult Index()
        {
            List<Conge> conges = context.Conges
                .Include(x => x.Employer )
                .ToList();
            List<Conge> cg = new List<Conge>();
            foreach (var x in conges)
            {
                if (x.confirmation_conge == 0)
                {
                    cg.Add(x);
                }
            }
            return View(cg);
        }

        // GET: CongeController/Details/5
        public ActionResult Details(int id)
        {
            Conge conge = context.Conges
                .Include(x => x.Employer)
                .FirstOrDefault(x => x.Id_conge == id);
            return View(conge);
        }

        // GET: CongeController/Create
        public ActionResult Create()
        {
            ViewBag.Listemployers = context.Employers.ToList();
            return View();
        }

        // POST: CongeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Conge conge)
        {
            try
            {
                if (ModelState.IsValid)// verif 3andnechy des contrainte fi modaile (?) accepte valeur nul ou non 
                {
                        conge.date_env_conge = DateTime.Now;
                        context.Conges.Add(conge);
                        context.SaveChanges();
                        ViewBag.create = "Congé ajoutée";
                        return RedirectToAction(nameof(Index));
                }
                ViewBag.Listemployers = context.Employers.ToList();
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: CongeController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Listemployers = context.Employers.ToList();
            Conge conge = context.Conges.Find(id);
            return View(conge);
        }

        // POST: CongeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Conge conge)
        {
            try
            {
                Conge conge1 = context.Conges.Find(id);
                conge1.type_conge = conge.type_conge;
                conge1.description_conge = conge.description_conge;
                conge1.date_env_conge = conge.date_env_conge;
                conge1.date_deb_conge=conge.date_deb_conge;
                conge1.date_fin_conge = conge.date_fin_conge;
                context.SaveChanges();
                ViewBag.modifier = " congé modifier ";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CongeController/Delete/5
        public ActionResult Delete(int id)
        {
            Conge conge=context.Conges.Find(id);
            return View(conge);
        }

        // POST: CongeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Conge conge)
        {
            try
            {
                context.Conges.Remove(conge);
                context.SaveChanges();
                ViewBag.supprimer = "Congé supprimer ";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ConfirmerConge()
        {
            List<Conge> conges = context.Conges
                .Include(x => x.Employer)
                .ToList();
            List<Conge> cg = new List<Conge>();
            foreach (var x in conges)
            {
                if (x.confirmation_conge == 1)
                {
                    cg.Add(x);
                }
            }
            return View(cg);
        }

        public ActionResult BtnConfirmerConge(int id)
        {
            ViewBag.Listemployers = context.Employers.Where(x => x.archive_emp == 0).ToList();
            Conge conge = context.Conges.Find(id);
            return View(conge);
        }

        // POST: CongeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BtnConfirmerConge(int id, Conge conge)
        {
            try
            {
                Conge conge1 = context.Conges.Find(id);
                conge1.confirmation_conge = 1;
                
                context.SaveChanges();
                ViewBag.modifier = " congé confirmer ";
                return RedirectToAction(nameof(ConfirmerConge));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult RefuserConge()
        {
            List<Conge> conges = context.Conges
                .Include(x => x.Employer)
                .ToList();
            List<Conge> cg = new List<Conge>();
            foreach (var x in conges)
            {
                if (x.confirmation_conge == -1)
                {
                    cg.Add(x);
                }
            }
            return View(cg);
        }

        public ActionResult BtnRefuserConge(int id)
        {
            ViewBag.Listemployers = context.Employers.Where(x => x.archive_emp == 0).ToList();
            Conge conge = context.Conges.Find(id);
            return View(conge);
        }

        // POST: CongeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BtnRefuserConge(int id, Conge conge)
        {
            try
            {
                Conge conge1 = context.Conges.Find(id);
                conge1.confirmation_conge = -1;

                context.SaveChanges();
                ViewBag.modifier = " congé confirmer ";
                return RedirectToAction(nameof(RefuserConge));
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjetDotnet/Controllers/PosteController.cs
using ProjetDotnet.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetDotnet.Data;
using Microsoft.AspNetCore.Authorization;

namespace ProjetDotnet.Controllers
{
    [Authorize]
    public class PosteController : Controller
    {
        private readonly GestionRHContext context;

        public PosteController(GestionRHContext context)
        {
            
            this.context=context;
        }
        // GET: PosteController
        public ActionResult Index()
        {
            List<Poste> postes = context.Postes
               .Include(x => x.Departement)
               .ToList();
            List<Poste> pst = new List<Poste>();
            foreach (var x in postes)
            {
                if (x.archive_poste == 0)
                {
                    pst.Add(x);
                }
            }
            return View(pst);
        }

        // GET: PosteController/Details/5
        public ActionResult Details(int id)
        {
                Poste poste = context.Postes
               .Include(x => x.Departement)
               .FirstOrDefault(x => x.Id_post == id); 
            return View(poste);
        }

        // GET: PosteController/Create
        public ActionResult Create()
        {
            ViewBag.ListDepartements = context.Departements.Where(x => x.archive_dep == 0).ToList();
            return View();
        }

        // POST: PosteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Poste poste)
        {
            try
            {
                if (ModelState.IsValid)// verif 3andnechy des contrainte fi modaile (?) accepte valeur nul ou non 
                {
                    if (context.Postes.Where(x => x.Nom_post == poste.Nom_post).Count() > 0)
                    {
                        ViewBag.ListDepartements = context.Departements.Where(x => x.archive_dep == 0).ToList(); // bech n3awed n3abi liste <select>
                        ViewBag.messageerror = "la poste existe";
                        return View(poste);
                    }
                    else
                    {
                        context.Postes.Add(poste);
                        context.SaveChanges();
                        ViewBag.create = "poste ajoutée";
                        return RedirectToAction(nameof(Index));
                    }


                }
                ViewBag.ListDepartements = context.Departements.Where(x => x.archive_dep == 0).ToList();
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: PosteController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.ListDepartements = context.Departements.Where(x => x.archive_dep == 0).ToList();
            Poste poste = context.Postes.Find(id);
            return View(poste);
        }

        // POST: PosteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Poste poste)
        {
            try
            {
                Poste pos = context.Postes.Find(id);
                pos.Nom_post=poste.Nom_post;
                pos.description_post = poste.description_post;
                pos.salaire_post = poste.salaire_post;
                pos.Id_dep = poste.Id_dep;
                context.SaveChanges();
                ViewBag.edit = "poste modifier";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PosteController/Delete/5
        public ActionResult Delete(int id)
        {
            Poste poste = context.Postes.Find(id);
            return View(poste);
            
        }

        // POST: PosteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Poste poste)
        {
            try
            {
                context.Postes.Remove(poste);
                context.SaveChanges();
                ViewBag.delate = "Poste supprimer ";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Archiver()
        {
            List<Poste> postes = context.Postes
               .Include(x => x.Departement)
               .ToList();
            List<Poste> pst = new List<Poste>();
            foreach (var x in postes)
            {
                if (x.archive_poste == 1)
                {
                    pst.Add(x);
                }
            }
            return View(pst);
        }

        public ActionResult PostArchiver(int id)
        {
            ViewBag.ListDepartements = context.Departements.Where(x => x.archive_dep == 0).ToList();
            Poste poste = context.Postes.Find(id);
            return View(poste);
        }
        // POST: PosteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostArchiver(int id, Poste poste)
        {
            try
            {
                Poste pos = context.Postes.Find(id);
                pos.archive_poste = 1;
                context.SaveChanges();
                ViewBag.edit = "poste archiver";
                return RedirectToAction(nameof(Archiver));
            }
            catch
            {
                return View();
            }
        }
        public ActionResult PostDesarchiver(int id)
        {
            ViewBag.ListDepartements = context.Departements.Where(x => x.archive_dep == 0).ToList();
            Poste poste = context.Postes.Find(id);
            return View(poste);
        }

        // POST: PosteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostDesarchiver(int id, Poste poste)
        {
            try
            {
                Poste pos = context.Postes.Find(id);
                pos.archive_poste = 0;
                context.SaveChanges();
                ViewBag.edit = "poste desarchiver";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjetDotnet/Views/Shared/_Footer.cshtml
  <!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        Tout ce que tu veux
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2023-2024 <a asp-area="" asp-controller="Home" asp-action="Index">Gestion RH</a>.</strong> Tous droits réservés.
</footer>

ProjetDotnet/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ProjetDotnet.Areas.Identity.Data

@inject SignInManager<Admin> SignInManager
@inject UserManager<Admin> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestion RH</title>
    <!-- jebnehom mel admin lte starter.html -->
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/adminlte/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <!-- zedneha fi les href w script lkol ~/adminlte/ -->
    <link rel="stylesheet" href="~/adminlte/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/adminlte/plugins/jqvmap/jqvmap.min.css">
    <!-- houni bedelna script bel styles jebneha mel loutaa-->
    @await RenderSectionAsync("Styles", required: false)


</head>
@if (SignInManager.IsSignedIn(User))
{
    String userId = UserManager.GetUserId(User);

    IdentityUser user = await UserManager.FindByIdAsync(userId);

    <body class="hold-transition sidebar-mini layout-fixed">
        <div class="wrapper">
            <partial name="_Navbar" /><!--appeler navbar layout-->

            <!-- Main Sidebar Container -->
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <!-- Brand Logo -->
                <a class="brand-link">
                    <img src="~/adminlte/dist/img/logoRH.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                    <span class="brand-text font-weight-light">Gestion RH</span>
                </a>

                <!-- Sidebar -->
                <div class="sidebar">
                    <!-- Sidebar user panel (optional) -->
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                        <div class="image">
                            <img src="~/adminlte/dist/img/AdminLTELogo.png" class="img-circle elevation-2" alt="User Image">
                        </div>
                        <div class="info">
                            <a class="d-block">
                                @{ String ema = user.Email; } @ema
                            </a>
                        </div>
                    </div>

                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                            <!-- Add icons to the links using the .nav-icon class
                                 with font-awesome or any other icon font library -->

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Departement" asp-action="Index">
                                    <i class="nav-icon fas fa-building"></i>
                                    <p>
                                        Departement
                                        <i class="right fas fa-angle-left"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Departement" asp-action="Index">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Liste Departements</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Departement" asp-action="Archiver">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Departements Archivées</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Poste" asp-action="Index">
                                    <i class="nav-icon fas fa-suitcase"></i>
                                    <p>
                                        Poste
                                        <i class="right fas fa-angle-left"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Poste" asp-action="Index">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Liste Postes</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Poste" asp-action="Archiver">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Postes Archivées</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Employer" asp-action="Index">
                                    <i class="nav-icon fas fa-users"></i>
                                    <p>
                                        Employéer
                                        <i class="right fas fa-angle-left"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Employer" asp-action="Index">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Liste Employées</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Employer" asp-action="Archiver">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Employées Archivées</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Conge" asp-action="Index">
                                    <i class="nav-icon fas fa-address-card"></i>
                                    <p>
                                        Conjé
                                        <i class="right fas fa-angle-left"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Conge" asp-action="Index">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Demande Conjé</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Conge" asp-action="ConfirmerConge">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Conjé Confirmé</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Conge" asp-action="RefuserConge">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Conjé Refuser</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Formation" asp-action="Index">
                                    <i class="nav-icon fas fa-graduation-cap"></i>
                                    <p>
                                        Formation
                                        <i class="right fas fa-angle-left"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Formation" asp-action="Index">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Liste Formations</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Formation" asp-action="Archive">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Formations Archivées</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            @{ Boolean emc = user.EmailConfirmed;}
                            @if (emc)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" href="/Identity/Account/Register">
                                        <i class="nav-icon fas fa-user-secret"></i>
                                        <p>
                                            Ajouter Admin
                                        </p>
                                    </a> 
                                </li>
                            } 
                            <li class="nav-item">
                                
                                <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button id="logout" type="submit" class="nav-link btn btn-link border-0"><i class="nav-icon fas fa-power-off"></i>Déconnexion</button>
                                </form>
                            </li>

                        </ul>
                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
                <!-- /.sidebar -->

            </aside>



            @RenderBody()

            <partial name="_Footer" />
        </div>
    </body>
}
else
{
    @RenderBody()
}
    <!--jebnehom mel admin lte -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/adminlte/dist/js/adminlte.min.js"></script>
    <script src="~/adminlte/plugins/moment/moment.min.js"></script>
    <script src="~/adminlte/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/adminlte/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/adminlte/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/adminlte/dist/js/pages/dashboard.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>

    <!--fin jbenehom-->
    @await RenderSectionAsync("Scripts", required: false)

</html>

ProjetDotnet/Views/Shared/_Navbar.cshtml
@inject ProjetDotnet.Data.GestionRHContext context ;
<!-- zedna ~/adminlte/ fi src .... -->
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Accueil </a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      
      
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">@{
                        int nb =context.Conges.Where(x => x.date_env_conge == DateTime.Now.Date && x.confirmation_conge==0).Count();
                    } @nb</span>
        </a>
            @if (nb > 0)
            {
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">@nb Notifications</span>
                  <div class="dropdown-divider"></div>
                  <a asp-area="" asp-controller="Conge" asp-action="Index" class="dropdown-item">
                      <i class="fas fa-address-card mr-2"></i>
                        @nb Nouvelles demandes de congés
                  </a>
                </div>
            }
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->
  