ProjetDotnet/Models/Formation.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjetDotnet.Models
{
    public class Formation
    {
        [Key] // cle pr
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id_formation { get; set; }
        [Required(ErrorMessage = "Nom est obligatoire. Veuillez la saisir.")]
        public string nom_formation { get; set; }
        [Required(ErrorMessage = "Description est obligatoire. Veuillez la saisir.")]
        public string description_formation { get; set; }

        public int? archive_formation { get; set; } = 0;
    }
}

ProjetDotnet/Controllers/FormationController.cs
using ProjetDotnet.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetDotnet.Data;
using Microsoft.AspNetCore.Authorization;

namespace ProjetDotnet.Controllers
{
    [Authorize]
    public class FormationController : Controller
    {
        private readonly GestionRHContext context;

        public FormationController(GestionRHContext context)
        {
            this.context=context;
        }
        // GET: FormationController
        public ActionResult Index()
        {
            List<Formation> formations = context.Formations.ToList();
            List<Formation> fr = new List<Formation>();
            foreach (var x in formations)
            {
                if (x.archive_formation == 0)
                {
                    fr.Add(x);
                }
            }
            return View(fr);
        }

        // GET: FormationController/Details/5
        public ActionResult Details(int id)
        {
            Formation formation = context.Formations.Find(id);
            return View(formation);
        }

        // GET: FormationController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FormationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Formation formation)
        {
            try
            {
                if (context.Formations.Where(x => x.nom_formation == formation.nom_formation)
                    .Count() > 0
                    )
                {
                    ViewBag.error = "Le formation existe !!!";
                    return View(formation);
                }
                context.Formations.Add(formation);
                context.SaveChanges();
                ViewBag.create = "Le formation ajouter !!!";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FormationController/Edit/5
        public ActionResult Edit(int id)
        {
            Formation formation=context.Formations.Find(id);
            return View(formation);
        }

        // POST: FormationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Formation formation)
        {
            try
            {
                Formation form = context.Formations.Find(id);
                form.nom_formation = formation.nom_formation;
                form.description_formation = formation.description_formation;
                context.SaveChanges();
                ViewBag.modifier = " Formation modifier ";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FormationController/Delete/5
        public ActionResult Delete(int id)
        {
            Formation formation = context.Formations.Find(id);
            return View(formation);
        }

        // POST: FormationController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Formation formation)
        {
            try
            {
                context.Formations.Remove(formation);
                context.SaveChanges();
                ViewBag.supprimer = "Formation supprimer ";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Archive()
        {
            List<Formation> formations = context.Formations.ToList();
            List<Formation> fr = new List<Formation>();
            foreach (var x in formations)
            {
                if (x.archive_formation == 1)
                {
                    fr.Add(x);
                }
            }
            return View(fr);
        }

        public ActionResult FormArchive(int id)
        {
            Formation formation = context.Formations.Find(id);
            return View(formation);
        }
        // POST: FormationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FormArchive(int id, Formation formation)
        {
            try
            {
                Formation form = context.Formations.Find(id);
                form.archive_formation = 1;
                context.SaveChanges();
                ViewBag.modifier = " Formation Archiver ";
                return RedirectToAction(nameof(Archive));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult FormDesarchive(int id)
        {
            Formation formation = context.Formations.Find(id);
            return View(formation);
        }

        // POST: FormationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FormDesarchive(int id, Formation formation)
        {
            try
            {
                Formation form = context.Formations.Find(id);
                form.archive_formation = 0;
                context.SaveChanges();
                ViewBag.modifier = " Formation modifier ";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjetDotnet/Views/Formation/Archive.cshtml
@model IEnumerable<ProjetDotnet.Models.Formation>

@{
    ViewData["Title"] = "Formation Archiver";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Liste des Formations Archivées</h1>

                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Accueil </a></li>
                        <li class="breadcrumb-item active">Liste des formations archivées</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <!-- TABLE: LATEST ORDERS -->
                    <div class="card">
                        <div class="card-header border-transparent">
                            
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Liste des formations</h3>
                                </div>
                                <div class="col-sm-6">
                                    <div class="card-tools float-right">
                                        <div class="input-group input-group-sm" style="width: 200px;">
                                            <input type="text" name="table_search" id="myInput" class="form-control " placeholder="Recherche">

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-default">
                                                    <i class="fas fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Nom</th>
                                            <th>Description</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody id="listedep">
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Id_formation)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.nom_formation)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.description_formation)
                                                </td>
                                                <td>
                                                    <button class="btn btn-danger btn-sm openDeleteModal" id="openDeleteModal" data-url="@Url.Action("FormDesarchive", "Formation", new { id = @item.Id_formation })">
                                                        <i class="fas fa-undo">
                                                        </i>
                                                    </button>
                                                    @* <a class="btn btn-warning btn-sm" asp-action="Desarchiver" asp-route-id="@item.Id_formation">
                                                        <i class="fas fa-undo">
                                                        </i>
                                                    </a> *@
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>

                            </div>
                            <!-- /.table-responsive -->
                        </div>

                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<div id="modalContainer"></div>
@section scripts {

    <script>
        $('.openDeleteModal').click(function () {
            var url = $(this).data('url');
            $.get(url, function (data) {
                $('#modalContainer').html(data);
                $('#deleteModal').modal('show');
            });
        });

        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#listedep tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}

ProjetDotnet/Views/Formation/Create.cshtml
@model ProjetDotnet.Models.Formation

@{
    ViewData["Title"] = "Ajouter Formation";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Liste des Formations</h1>

                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Accueil </a></li>
                        <li class="breadcrumb-item"><a asp-area="" asp-controller="Formation" asp-action="Index">Liste des formations </a></li>
                        <li class="breadcrumb-item active">Ajouter formations</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Ajouter Formation</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label asp-for="nom_formation" class="control-label">Nom</label>
                                    <input asp-for="nom_formation" class="form-control" />
                                    <span asp-validation-for="nom_formation" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="description_formation" class="control-label">Description</label>
                                    <textarea asp-for="description_formation" class="form-control" rows="3" placeholder="Enter ..."></textarea>
                                    <span asp-validation-for="description_formation" class="text-danger"></span>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <a class="btn btn-outline-secondary " asp-controller="Formation" asp-action="Index">Retour</a>
                                <button type="submit" value="Create" class="btn btn-outline-primary float-right">Enregistrer</button>
                            </div>
                        </form>
                        <span class="bg-danger text-white">@ViewBag.error</span>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetDotnet/Views/Formation/Edit.cshtml
@model ProjetDotnet.Models.Formation

@{
    ViewData["Title"] = "Modifier Formation";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Liste des Formations</h1>

                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Accueil </a></li>
                        <li class="breadcrumb-item"><a asp-area="" asp-controller="Formation" asp-action="Index">Liste des formations </a></li>
                        <li class="breadcrumb-item active">Modifier formation</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Modifier Formation</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label asp-for="nom_formation" class="control-label">Nom</label>
                                    <input asp-for="nom_formation" class="form-control" />
                                    <span asp-validation-for="nom_formation" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="description_formation" class="control-label">Description</label>
                                    <textarea asp-for="description_formation" class="form-control" rows="3" placeholder="Enter ..."></textarea>
                                    <span asp-validation-for="description_formation" class="text-danger"></span>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <a class="btn btn-outline-secondary " asp-controller="Formation" asp-action="Index">Retour</a>
                                <button type="submit" value="Edit" class="btn btn-outline-primary float-right">Modifier</button>
                            </div>
                        </form>
                        <span class="bg-danger text-white">@ViewBag.error</span>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetDotnet/Views/Formation/FormArchive.cshtml
@model ProjetDotnet.Models.Formation

@{
    ViewData["Title"] = "Archiver Formation";
}

<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form asp-action="FormArchive">
                <input type="hidden" asp-for="Id_formation" />
                <input type="hidden" asp-for="nom_formation" />
                <input type="hidden" asp-for="description_formation" />
                <div class="modal-header">
                    <h5 class="modal-title">Confirmer l'archivation</h5>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <p>Voulez-vous vraiment archiver cet formation "@Model.nom_formation" ?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>

                    <input type="submit" value="Archiver" class="btn btn-outline-danger float-right" />

                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetDotnet/Views/Formation/FormDesarchive.cshtml
@model ProjetDotnet.Models.Formation

@{
    ViewData["Title"] = "Desarchiver Formation";
}

<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form asp-action="FormDesarchive">
                <input type="hidden" asp-for="Id_formation" />
                <input type="hidden" asp-for="nom_formation" />
                <input type="hidden" asp-for="description_formation" />
                <div class="modal-header">
                    <h5 class="modal-title">Confirmer la Désarchivation</h5>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <p>Voulez-vous vraiment désarchiver cet formation "@Model.nom_formation" ?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>

                    <input type="submit" value="Désarchiver" class="btn btn-outline-danger float-right" />

                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetDotnet/Views/Formation/Index.cshtml
@model IEnumerable<ProjetDotnet.Models.Formation>

@{
    ViewData["Title"] = "Liste Formation";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Liste des Formations</h1>

                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Accueil </a></li>
                        <li class="breadcrumb-item active">Liste des formations</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <!-- TABLE: LATEST ORDERS -->
                    <div class="card">
                        <div class="card-header border-transparent">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Liste des formations</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a asp-action="Create" class="btn btn-outline-info float-right">Ajouter <i class="fa fa-plus-circle"></i></a>
                                </div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-sm-12">
                                    <div class="card-tools ">
                                        <div class="input-group input-group-sm" style="width: 200px;">
                                            <input type="text" name="table_search" id="myInput" class="form-control " placeholder="Recherche">

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-default">
                                                    <i class="fas fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Nom</th>
                                            <th>Description</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody id="listedep">
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Id_formation)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.nom_formation)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.description_formation)
                                                </td>
                                                <td>
                                                    <div class="row">
                                                        <div class="col-6">
                                                            <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@item.Id_formation">
                                                                <i class="fas fa-pencil-alt">
                                                                </i>
                                                            </a>
                                                        </div>
                                                        <div class="col-6">
                                                            <button class="btn btn-danger btn-sm openDeleteModal" id="openDeleteModal" data-url="@Url.Action("FormArchive", "Formation", new { id = @item.Id_formation })">
                                                                <i class="fas fa-trash">
                                                                </i>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>

                            </div>
                            <!-- /.table-responsive -->
                        </div>

                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<div id="modalContainer"></div>
@section scripts {

    <script>
        $('.openDeleteModal').click(function () {
            var url = $(this).data('url');
            $.get(url, function (data) {
                $('#modalContainer').html(data);
                $('#deleteModal').modal('show');
            });
        });

        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#listedep tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}