ProjetDotnet/Controllers/EmployerController.cs
using ProjetDotnet.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetDotnet.Data;
using Microsoft.AspNetCore.Authorization;

namespace ProjetDotnet.Controllers
{
    [Authorize]
    public class EmployerController : Controller
    {
        private readonly GestionRHContext context;

        public EmployerController(GestionRHContext context)
        {
            this.context = context;
        }
        // GET: EmployerController
        public ActionResult Index()
        {
            List<Employer> employers = context.Employers
                .Include(x => x.Poste)
                .ToList();
            List<Employer> emp = new List<Employer>();
            List<int> nbT = new List<int>();
            List<int> nbF = new List<int>();
            foreach (var i in employers)
            {
                if (i.archive_emp == 0)
                {
                    nbT.Add (context.Taches.Where(x => x.employerId == i.Id_emp).Count());
                    nbF.Add(context.EmployerFormations.Where(x => x.employerId == i.Id_emp).Count());
                    emp.Add(i);
                }
            }
            ViewBag.CountTache = nbT;
            ViewBag.CountFormation = nbF;
            return View(emp);
        }

        // GET: EmployerController/Details/5
        public ActionResult Details(int id)
        {
            Employer employer = context.Employers
                .Include(x => x.Poste)
                .FirstOrDefault(x => x.Id_emp == id) ;
            return View(employer);
        }

        

        // GET: EmployerController/Create
        public ActionResult Create()
        {
            ViewBag.Listpostes = context.Postes.Where(x => x.archive_poste== 0).ToList();
            return View();
        }

        // POST: EmployerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Employer employer)
        {
            try
            {
                if (ModelState.IsValid)// verif 3andnechy des contrainte fi modaile (?) accepte valeur nul ou non 
                {
                    if (context.Employers.Where(x => x.cin_emp == employer.cin_emp).Count() > 0 )
                    {
                        ViewBag.Listpostes = context.Postes.Where(x => x.archive_poste == 0).ToList(); // bech n3awed n3abi liste <select>
                        ViewBag.messageerror = "la cin de l'employer existe";
                        return View(employer);
                    }
                    else
                    {
                        if (context.Employers.Where(x => x.email_emp == employer.email_emp).Count() > 0)
                        {
                            ViewBag.Listpostes = context.Postes.Where(x => x.archive_poste == 0).ToList(); // bech n3awed n3abi liste <select>
                            ViewBag.messageerror = "L'adresse e-mail de l'employer existe";
                            return View(employer);
                        }
                        else
                        {
                            context.Employers.Add(employer);
                            context.SaveChanges();
                            ViewBag.create = "employers ajoutée";
                            return RedirectToAction(nameof(Index));
                        }
                    }


                }
                ViewBag.Listpostes = context.Postes.Where(x => x.archive_poste == 0).ToList();
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: EmployerController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Listpostes = context.Postes.Where(x => x.archive_poste == 0).ToList();
            Employer employer = context.Employers.Find(id);
            return View(employer);
        }

        // POST: EmployerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Employer employer)
        {
            try
            {
                Employer emp = context.Employers.Find(id);
                emp.cin_emp=employer.cin_emp;
                emp.nom_emp=employer.nom_emp;
                emp.prenom_emp=employer.prenom_emp;
                emp.date_naissance_emp = employer.date_naissance_emp;
                emp.sexe_emp=employer.sexe_emp;
                emp.adresse_emp=employer.adresse_emp;
                emp.numtell_emp=employer.numtell_emp;
                emp.email_emp=employer.email_emp;
                emp.date_embauche_emp = employer.date_embauche_emp;
                employer.psw_emp=employer.psw_emp;
                emp.ville_emp=employer.ville_emp;
                emp.Id_post=employer.Id_post;
                
                context.SaveChanges();
                ViewBag.modifier = " employer modifier ";
                return RedirectToAction(nameof(Index));
                
            }
            catch
            {
                return View();
            }
        }

        // GET: EmployerController/Delete/5
        public ActionResult Delete(int id)
        {
            Employer employer = context.Employers.Find(id);
            return View(employer);
        }

        // POST: EmployerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Employer employer)
        {
            try
            {
                context.Employers.Remove(employer);
                context.SaveChanges();
                ViewBag.supprimer = "employer supprimer ";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Archiver()
        {
            List<Employer> employers = context.Employers
                .Include(x => x.Poste)
                .ToList();
            List<Employer> emp = new List<Employer>();
            foreach (var x in employers)
            {
                if (x.archive_emp == 1)
                {
                    emp.Add(x);
                }
            }
            return View(emp);
        }

        public ActionResult EmpArchiver(int id)
        {
            ViewBag.Listpostes = context.Postes.Where(x => x.archive_poste == 0).ToList();
            Employer employer = context.Employers.Find(id);
            return View(employer);
        }

        // POST: EmployerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmpArchiver(int id, Employer employer)
        {
            try
            {
                Employer emp = context.Employers.Find(id);
                emp.archive_emp = 1;
                

                context.SaveChanges();
                ViewBag.modifier = " employer Archiver ";
                return RedirectToAction(nameof(Archiver));

            }
            catch
            {
                return View();
            }
        }

        public ActionResult EmpDesarchiver(int id)
        {
            ViewBag.Listpostes = context.Postes.Where(x => x.archive_poste == 0).ToList();
            Employer employer = context.Employers.Find(id);
            return View(employer);
        }

        // POST: EmployerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmpDesarchiver(int id, Employer employer)
        {
            try
            {
                Employer emp = context.Employers.Find(id);
                emp.archive_emp =0;
                

                context.SaveChanges();
                ViewBag.modifier = " employer Desarchiver ";
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View();
            }
        }
    }
}

ProjetDotnet/Controllers/EmployerFormationController.cs
using ProjetDotnet.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetDotnet.Data;
using Microsoft.AspNetCore.Authorization;

namespace ProjetDotnet.Controllers
{
    [Authorize]
    public class EmployerFormationController : Controller
    {
        private readonly GestionRHContext context;

        public EmployerFormationController(GestionRHContext context)
        {

            this.context=context;
        }
        // GET: EmployerFormationController
        public ActionResult Index(int id)
        {
            List<EmployerFormation> employerFormations = context.EmployerFormations
                .Include(x => x.Employer)
                .Include(y => y.Formation)
                .Where(x => x.employerId == id)
                .ToList();
            ViewBag.ListEmployers = context.Employers.Where(x => x.Id_emp == id).ToList();
            return View(employerFormations);
        }

        // GET: EmployerFormationController/Details/5
        public ActionResult Details(int id)
        {
            EmployerFormation employerFormation = context.EmployerFormations
                .Include(x => x.Employer)
                .Include(y => y.Formation)
                .FirstOrDefault(x => x.Id_empform == id) ;
            return View(employerFormation);
        }

        // GET: EmployerFormationController/Create
        public ActionResult Create(int id)
        {
            ViewBag.ListEmployers = context.Employers.Where(x => x.Id_emp == id).ToList();
            ViewBag.Listformations = context.Formations.Where(x => x.archive_formation == 0).ToList();
            return View();
        }

        // POST: EmployerFormationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int idep,EmployerFormation employerFormation)
        {
            try
            {
                if (ModelState.IsValid)// verif 3andnechy des contrainte fi modaile (?) accepte valeur nul ou non 
                {
                    context.EmployerFormations.Add(employerFormation);
                    context.SaveChanges();
                    ViewBag.create = "formation ajoutée pour cette employer";
                    ViewBag.ListEmployers = context.Employers.Where(x => x.Id_emp == idep).ToList();
                    return RedirectToAction("Index", "Employer");
                }
                ViewBag.ListEmployers = context.Employers.Where(x => x.Id_emp == idep).ToList();
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: EmployerFormationController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Listemployers = context.Employers.Where(x => x.archive_emp == 0).ToList();
            ViewBag.Listformations = context.Formations.Where(x => x.archive_formation == 0).ToList();
            EmployerFormation employerFormation = context.EmployerFormations.Find(id);
            return View(employerFormation);
        }

        // POST: EmployerFormationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,EmployerFormation employerFormation)
        {
            try
            {
                EmployerFormation employerFormation1 = context.EmployerFormations.Find(id);
                employerFormation1.date_fin_empform=DateTime.Now;
                ViewBag.edit = "formation terminer";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmployerFormationController/Delete/5
        public ActionResult Delete(int id)
        {
            EmployerFormation employerFormation = context.EmployerFormations.Find(id);
            return View(employerFormation);
        }

        // POST: EmployerFormationController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, EmployerFormation employerFormation)
        {
            try
            {
                context.EmployerFormations.Remove(employerFormation);
                context.SaveChanges();
                ViewBag.supprimer = "employer formation supprimer ";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        // raj3elna kol employer 9adeh andou men formation 
        public int CountFormation(int id) // id employer 
        {
            //var count = context.EmployerFormations.Count(f => f.employerId == id);
            var count = context.EmployerFormations.Where(x => x.employerId == id).Count();

            return count;
        }
    }
}

ProjetDotnet/Controllers/TacheController.cs
using ProjetDotnet.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetDotnet.Data;
using Microsoft.AspNetCore.Authorization;

namespace ProjetDotnet.Controllers
{
    [Authorize]
    public class TacheController : Controller
    {
        private readonly GestionRHContext context;

        public TacheController(GestionRHContext context)
        {
            this.context=context;
        }
        // GET: TacheController
        public ActionResult Index(int id)
        {
            List<Tache> taches = context.Taches
                .Include(x => x.Employer)
                .Where(x => x.employerId == id)
                .ToList();
            Employer emp = context.Employers.Find(id);
            ViewBag.ListEmployers = context.Employers.Where(x => x.Id_emp == id).ToList();
            ViewBag.Listpostes = context.Postes.Where(x => x.Id_post == emp.Id_post).ToList();
            return View(taches);
        }

        // GET: TacheController/Details/5
        public ActionResult Details(int id)
        {
            Tache tache = context.Taches
                .Include(x => x.Employer)
                .FirstOrDefault(x => x.Id_tache == id);
            return View(tache);
        }

        // GET: TacheController/Create
        public ActionResult Create(int id)
        {
            ViewBag.ListEmployers = context.Employers.Where(x => x.Id_emp == id).ToList();
            return View();
        }

        // POST: TacheController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int idx,Tache tache)
        {
            try
            {
                if (ModelState.IsValid)// verif 3andnechy des contrainte fi modaile (?) accepte valeur nul ou non 
                {
                    context.Taches.Add(tache);
                    context.SaveChanges();
                    ViewBag.create = "tache ajoutée";
                    return RedirectToAction("Index", "Employer");
                }
                ViewBag.ListEmployers = context.Employers.Where(x => x.Id_emp == idx).ToList();
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: TacheController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Listemployers = context.Employers.Where(x => x.archive_emp == 0).ToList();
            Tache tache = context.Taches.Find(id);
            return View(tache);
        }

        // POST: TacheController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Tache tache)
        {
            try
            {
                Tache tach = context.Taches.Find(id);
                tach.date_deb_tache=tache.date_deb_tache;
                //tach.date_fin_tache = tache.date_fin_tache;
                tach.description_rapp=tach.description_rapp;
                tach.employerId=tache.employerId;
                context.SaveChanges();
                ViewBag.modifier = " tache modifier ";
                return RedirectToAction(nameof(Index));
                
            }
            catch
            {
                return View();
            }
        }

        // GET: TacheController/Delete/5
        public ActionResult Delete(int id)
        {
            Tache tache = context.Taches.Find(id);
            return View(tache);
        }

        // POST: TacheController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Tache tache)
        {
            try
            {
                context.Taches.Remove(tache);
                context.SaveChanges();
                ViewBag.supprimer = "tache supprimer ";
                return RedirectToAction("Index", "Employer");
            }
            catch
            {
                return View();
            }
        }

        // GET: TacheController/Edit/5
        public ActionResult TacheTerminer(int id)
        {
            ViewBag.Listemployers = context.Employers.Where(x => x.archive_emp == 0).ToList();
            Tache tache = context.Taches.Find(id);
            return View(tache);
        }

        // POST: TacheController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TacheTerminer(int id, Tache tache)
        {
            try
            {
                Tache tach = context.Taches.Find(id);
                tach.date_fin_tache = DateTime.Now;
                tach.description_rapp = tache.description_rapp;
                context.SaveChanges();
                ViewBag.modifier = " tache terminer ";
                return RedirectToAction("Index", "Employer");

            }
            catch
            {
                return View();
            }
        }
    }
}

ProjetDotnet/Views/Employer/EmpArchiver.cshtml
@model ProjetDotnet.Models.Employer

@{
    ViewData["Title"] = "Archiver Employer";
}

<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form asp-action="EmpArchiver">
                <input type="hidden" asp-for="Id_emp" />
                <input type="hidden" asp-for="nom_emp" />
                <input type="hidden" asp-for="prenom_emp" />
                <input type="hidden" asp-for="date_naissance_emp" />
                <input type="hidden" asp-for="date_embauche_emp" />
                <input type="hidden" asp-for="sexe_emp" />
                <input type="hidden" asp-for="ville_emp" />
                <input type="hidden" asp-for="adresse_emp" />
                <input type="hidden" asp-for="numtell_emp" />
                <input type="hidden" asp-for="email_emp" />
                <input type="hidden" asp-for="psw_emp" />
                <input type="hidden" asp-for="Id_post" />

                <div class="modal-header">
                    <h5 class="modal-title">Confirmer l'archivation</h5>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <p>Voulez-vous vraiment archiver l'employer "@Model.nom_emp  @Model.prenom_emp" ?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>

                    <input type="submit" value="Archiver" class="btn btn-outline-danger float-right" />

                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetDotnet/Views/Employer/EmpDesarchiver.cshtml
@model ProjetDotnet.Models.Employer

@{
    ViewData["Title"] = "Desarchiver Employer";
}

<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form asp-action="EmpDesarchiver">
                <input type="hidden" asp-for="Id_emp" />
                <input type="hidden" asp-for="nom_emp" />
                <input type="hidden" asp-for="prenom_emp" />
                <input type="hidden" asp-for="date_naissance_emp" />
                <input type="hidden" asp-for="date_embauche_emp" />
                <input type="hidden" asp-for="sexe_emp" />
                <input type="hidden" asp-for="ville_emp" />
                <input type="hidden" asp-for="adresse_emp" />
                <input type="hidden" asp-for="numtell_emp" />
                <input type="hidden" asp-for="email_emp" />
                <input type="hidden" asp-for="psw_emp" />
                <input type="hidden" asp-for="Id_post" />

                <div class="modal-header">
                    <h5 class="modal-title">Confirmer la désarchivation</h5>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <p>Voulez-vous vraiment désarchiver l'employer "@Model.nom_emp  @Model.prenom_emp" ?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>

                    <input type="submit" value="Désarchiver" class="btn btn-outline-danger float-right" />

                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetDotnet/Views/Employer/Index.cshtml
@model IEnumerable<ProjetDotnet.Models.Employer>

@{
    ViewData["Title"] = "Liste Employer";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Liste des Employées</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Accueil </a></li>
                        <li class="breadcrumb-item active">Liste des employées</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <!-- TABLE: LATEST ORDERS -->
                    <div class="card">
                        <div class="card-header border-transparent">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Liste des employées</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a asp-action="Create" class="btn btn-outline-info float-right">Ajouter <i class="fa fa-plus-circle"></i></a>
                                </div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-sm-12">
                                    <div class="card-tools ">
                                        <div class="input-group input-group-sm" style="width: 200px;">
                                            <input type="text" name="table_search" id="myInput" class="form-control " placeholder="Recherche">

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-default">
                                                    <i class="fas fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>CIN</th>
                                            <th>Nom & Prénom</th>
                                            <th>Téléphone</th>
                                            <th>Poste</th>
                                            <th>Tache</th>
                                            <th>Formation</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody id="listedep">
                                        @{int i=0;}
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.cin_emp)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.nom_emp) @Html.DisplayFor(modelItem => item.prenom_emp)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.numtell_emp)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Poste.Nom_post)
                                                </td>
                                                <td>
                                                    @if(ViewBag.CountTache[i]>0)
                                                    {
                                                        int x = item.Id_emp;
                                                        <a asp-area="" asp-controller="Tache" asp-action="Index" asp-route-id="@x">Liste des taches </a>
                                                    }
                                                    else
                                                    {
                                                        int x = item.Id_emp;
                                                        <a asp-area="" asp-controller="Tache" asp-action="Create" asp-route-id="@x">Ajouter Tache</a>
                                                    }
                                                </td>
                                                <td>
                                                    @if (ViewBag.CountFormation[i] > 0)
                                                    {
                                                        int x = item.Id_emp;
                                                        <a asp-area="" asp-controller="EmployerFormation" asp-action="Index" asp-route-id="@x">Liste des formations </a>
                                                    }
                                                    else
                                                    {
                                                        int x = item.Id_emp;
                                                        <a asp-area="" asp-controller="EmployerFormation" asp-action="Create" asp-route-id="@x">Ajouter Formation</a>
                                                    }
                                                </td>
                                                <td>
                                                    <a class="btn btn-info btn-sm" asp-action="Details" asp-route-id="@item.Id_emp">
                                                        <i class="fas fa-eye"></i>
                                                    </a>
                                                    <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@item.Id_emp">
                                                        <i class="fas fa-pencil-alt">
                                                        </i>
                                                    </a>
                                                    <button class="btn btn-danger btn-sm openDeleteModal" id="openDeleteModal" data-url="@Url.Action("EmpArchiver", "Employer", new { id = @item.Id_emp })">
                                                        <i class="fas fa-trash">
                                                        </i>
                                                    </button>
                                                    @* <a class="btn btn-danger btn-sm" asp-action="Archiver" asp-route-id="@item.Id_emp">
                                                        <i class="fas fa-trash">
                                                        </i>
                                                    </a> *@
                                                </td>
                                            </tr>
                                            i++;
                                        }
                                    </tbody>
                                </table>

                            </div>
                            <!-- /.table-responsive -->
                        </div>

                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<div id="modalContainer"></div>
@section scripts {

    <script>
        $('.openDeleteModal').click(function () {
            var url = $(this).data('url');
            $.get(url, function (data) {
                $('#modalContainer').html(data);
                $('#deleteModal').modal('show');
            });
        });

        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#listedep tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}