ProjetDotnet/Models/Departement.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjetDotnet.Models
{
    public class Departement
    {
        [Key] // cle pr
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id_dep { get; set; }

        [Required(ErrorMessage = "id est obligatoire. Veuillez la saisir.")] /// champs non vide 
        public string? Nom_dep { get; set; }
        [Required(ErrorMessage = "Description est obligatoire. Veuillez la saisir.")]
        public string description_dep { get; set; }

        public int? archive_dep { get; set; } = 0;

        public virtual ICollection<Poste> Postes { get; set; } = new List<Poste>();
    }
}

ProjetDotnet/Controllers/DepartementController.cs
using ProjetDotnet.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetDotnet.Data;
using Microsoft.AspNetCore.Authorization;

namespace ProjetDotnet.Controllers
{
    [Authorize]
    public class DepartementController : Controller
    {
        private readonly GestionRHContext context;

        public DepartementController(GestionRHContext context)
        {
            this.context=context;
            
        }
        // GET: DepartementController
        public ActionResult Index()
        {
            List<Departement> departements = context.Departements.ToList();
            List<Departement> dep = new List<Departement>();
            foreach (var x in departements)
            {
                if (x.archive_dep == 0)
                {
                    dep.Add(x);
                }
            }
            return View(dep);
        }

        // GET: DepartementController/Details/5
        public ActionResult Details(int id)
        {
            Departement departement = context.Departements.Find(id);
            return View(departement);
        }

        // GET: DepartementController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DepartementController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Departement departement)
        {
            try
            {
                if (context.Departements.Where(x => x.Id_dep == departement.Id_dep)
                    .Count() > 0
                    )
                {
                    ViewBag.error = "Le departement existe !!!";
                    return View(departement);
                }
                context.Departements.Add(departement);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DepartementController/Edit/5
        public ActionResult Edit(int id)
        {
            Departement departement = context.Departements.Find(id);
            return View(departement);
        }

        // POST: DepartementController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Departement departement)
        {
            try
            {
                Departement dep = context.Departements.Find(id);
                dep.Id_dep=departement.Id_dep;
                dep.Nom_dep=departement.Nom_dep;
                dep.description_dep = departement.description_dep;
                //dep.archive_dep = departement.archive_dep;
                context.SaveChanges();
                ViewBag.modifier = " departement modifier ";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DepartementController/Delete/5
        public ActionResult Delete(int id)
        {
            Departement departement = context.Departements.Find(id);
            return View(departement);
        }

        // POST: DepartementController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Departement departement)
        {
            try
            {
                context.Departements.Remove(departement);
                context.SaveChanges();
                ViewBag.supprimer = "departement supprimer ";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //archiver
        public ActionResult Archiver()
        {
            List<Departement> departements = context.Departements.ToList();
            List<Departement> dep = new List<Departement>();
            foreach (var x in departements)
            {
                if (x.archive_dep == 1)
                {
                    dep.Add(x);
                }
            }
            return View(dep);
        }

        public ActionResult depArchiver(int id)
        {
            Departement departement = context.Departements.Find(id);
            return View(departement);
        }
        // POST: DepartementController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult depArchiver(int id, Departement departement)
        {
            try
            {
                Departement dep = context.Departements.Find(id);
               // dep.Id_dep = departement.Id_dep;
               // dep.Nom_dep = departement.Nom_dep;
               // dep.description_dep = departement.description_dep;
                dep.archive_dep = 1;
                context.SaveChanges();
                ViewBag.archiver = " departement archiver ";
                return RedirectToAction(nameof(Archiver));
            }
            catch
            {
                return View();
            }
        }
        public ActionResult depDesarchiver(int id)
        {
            Departement departement = context.Departements.Find(id);
            return View(departement);
        }

        // POST: DepartementController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult depDesarchiver(int id, Departement departement)
        {
            try
            {
                Departement dep = context.Departements.Find(id);
                //dep.Id_dep = departement.Id_dep;
               // dep.Nom_dep = departement.Nom_dep;
               // dep.description_dep = departement.description_dep;
                dep.archive_dep = 0;
                context.SaveChanges();
                ViewBag.desarchiver = " departement Desarchiver ";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }

    

}

ProjetDotnet/Views/Departement/Archiver.cshtml
@model IEnumerable<ProjetDotnet.Models.Departement>

@{
    ViewData["Title"] = "Département Archiver";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Liste des Départements Archivées</h1>

                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Accueil </a></li>
                        <li class="breadcrumb-item active">Liste des départements archivées</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <!-- TABLE: LATEST ORDERS -->
                    <div class="card">
                        <div class="card-header border-transparent">
                            
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Liste des départements</h3>
                                </div>
                                <div class="col-sm-6">
                                    <div class="card-tools float-right">
                                        <div class="input-group input-group-sm" style="width: 200px;">
                                            <input type="text" name="table_search" id="myInput" class="form-control " placeholder="Recherche">

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-default">
                                                    <i class="fas fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Nom</th>
                                            <th>Description</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody id="listedep">
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Id_dep)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Nom_dep)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.description_dep)
                                                </td>
                                                <td>
                                                    <button class="btn btn-danger btn-sm openDeleteModal" id="openDeleteModal" data-url="@Url.Action("depDesarchiver", "Departement", new { id = @item.Id_dep })">
                                                        <i class="fas fa-undo">
                                                        </i>
                                                    </button>
                                                    @* <a class="btn btn-warning btn-sm" asp-action="Desarchiver" asp-route-id="@item.Id_dep">
                                                        <i class="fas fa-undo">
                                                        </i>
                                                    </a> *@
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>

                            </div>
                            <!-- /.table-responsive -->
                        </div>

                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<div id="modalContainer"></div>
@section scripts {

    <script>
        $('.openDeleteModal').click(function () {
            var url = $(this).data('url');
            $.get(url, function (data) {
                $('#modalContainer').html(data);
                $('#deleteModal').modal('show');
            });
        });

        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#listedep tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}

ProjetDotnet/Views/Departement/Create.cshtml
@model ProjetDotnet.Models.Departement

@{
    ViewData["Title"] = "Ajouter Département";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Liste des Départements</h1>

                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Accueil </a></li>
                        <li class="breadcrumb-item"><a asp-area="" asp-controller="Departement" asp-action="Index">Liste des départements </a></li>
                        <li class="breadcrumb-item active">Ajouter département</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Ajouter Département</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action ="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label asp-for="Nom_dep" class="control-label">Nom</label>
                                    <input asp-for="Nom_dep" class="form-control" type="text" placeholder="Enter nom" />
                                    <span asp-validation-for="Nom_dep" class="text-danger"></span>
                                </div>

                                <div class="form-group">
                                    <label asp-for="description_dep" class="control-label">Description</label>
                                    <textarea asp-for="description_dep" class="form-control" rows="3" placeholder="Enter ..."></textarea>
                                    <span asp-validation-for="description_dep" class="text-danger"></span>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <a class="btn btn-outline-secondary " asp-controller="Departement" asp-action="Index">Retour</a>
                                <button type="submit" value="Create" class="btn btn-outline-primary float-right">Enregistrer</button>
                            </div>
                        </form>
                        <span class="bg-danger text-white">@ViewBag.error</span>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetDotnet/Views/Departement/Edit.cshtml
@model ProjetDotnet.Models.Departement

@{
    ViewData["Title"] = "Modifier Département";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Liste des Départements</h1>

                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Accueil </a></li>
                        <li class="breadcrumb-item"><a asp-area="" asp-controller="Departement" asp-action="Index">Liste des départements </a></li>
                        <li class="breadcrumb-item active">Modifier département</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Modifier Département</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Id_dep" />
                            <div class="card-body">
                                <div class="form-group">
                                    <label asp-for="Nom_dep" class="control-label">Nom</label>
                                    <input asp-for="Nom_dep" class="form-control" type="text" placeholder="Enter nom" />
                                    <span asp-validation-for="Nom_dep" class="text-danger"></span>
                                </div>

                                <div class="form-group">
                                    <label asp-for="description_dep" class="control-label">Description</label>
                                    <textarea asp-for="description_dep" class="form-control" rows="3" placeholder="Enter ..."></textarea>
                                    <span asp-validation-for="Nom_dep" class="text-danger"></span>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <a class="btn btn-outline-secondary " asp-controller="Departement" asp-action="Index">Retour</a>
                                <button type="submit" value="Create" class="btn btn-outline-primary float-right">Modifier</button>
                            </div>
                        </form>
                        <span class="bg-danger text-white">@ViewBag.error</span>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetDotnet/Views/Departement/Index.cshtml
@model IEnumerable<ProjetDotnet.Models.Departement>

@{
    ViewData["Title"] = "Liste Département";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Liste des Départements</h1>

                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Accueil </a></li>
                        <li class="breadcrumb-item active">Liste des départements</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-md-12">
                    <!-- TABLE: LATEST ORDERS -->
                    <div class="card">
                        <div class="card-header border-transparent">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Liste des départements</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a asp-action="Create" class="btn btn-outline-info float-right">Ajouter <i class="fa fa-plus-circle"></i></a>
                                </div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-sm-12">
                                    <div class="card-tools ">
                                        <div class="input-group input-group-sm" style="width: 200px;">
                                            <input type="text" name="table_search" id="myInput" class="form-control " placeholder="Recherche">

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-default">
                                                    <i class="fas fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Nom</th>
                                            <th>Description</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody id="listedep">
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Id_dep)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Nom_dep)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.description_dep)
                                                </td>
                                                <td>
                                                    <div class="row">
                                                        <div class="col-6">
                                                            <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@item.Id_dep">
                                                                <i class="fas fa-pencil-alt">
                                                                </i>
                                                            </a>
                                                        </div>
                                                        <div class="col-6">
                                                            <button class="btn btn-danger btn-sm openDeleteModal" id="openDeleteModal" data-url="@Url.Action("depArchiver", "Departement", new { id = @item.Id_dep })">
                                                                <i class="fas fa-trash">
                                                                </i>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>

                            </div>
                            <!-- /.table-responsive -->
                        </div>

                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<div id="modalContainer"></div>
@section scripts {

    <script>
        $('.openDeleteModal').click(function () {
            var url = $(this).data('url');
            $.get(url, function (data) {
                $('#modalContainer').html(data);
                $('#deleteModal').modal('show');
            });
        });

        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#listedep tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}

ProjetDotnet/Views/Departement/depArchiver.cshtml
@model ProjetDotnet.Models.Departement

@{
    ViewData["Title"] = "Archiver Département";
}

<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form asp-action="depArchiver">
                <input type="hidden" asp-for="Id_dep" />
                <input type="hidden" asp-for="Nom_dep" />
                <input type="hidden" asp-for="description_dep" />
                <div class="modal-header">
                    <h5 class="modal-title">Confirmer l'archivation</h5>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <p>Voulez-vous vraiment archiver le département "@Model.Nom_dep" ?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>

                    <input type="submit" value="Archiver" class="btn btn-outline-danger float-right" />

                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetDotnet/Views/Departement/depDesarchiver.cshtml
@model ProjetDotnet.Models.Departement

@{
    ViewData["Title"] = "Desarchiver Département";
}

<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form asp-action="depDesarchiver">
                <input type="hidden" asp-for="Id_dep" />
                <input type="hidden" asp-for="Nom_dep" />
                <input type="hidden" asp-for="description_dep" />
                <div class="modal-header">
                    <h5 class="modal-title">Confirmer la Désarchivation'</h5>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <p>Voulez-vous vraiment désarchiver le département "@Model.Nom_dep" ?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>

                    <input type="submit" value="Désarchiver" class="btn btn-outline-danger float-right" />

                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}